services:
  deadmanswitch:
    build: .
    image: "ghcr.io/oasisprotocol/deadmanswitch"
    platform: linux/amd64
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - CONTRACT_ADDRESS=${CONTRACT_ADDRESS}
      - SAPPHIRE_RPC_URL=${SAPPHIRE_RPC_URL}
    ports:
      - "5000:5000"